apiVersion: v1
description: Helm chart for the Interplanetary File System
name: ipfs
version: 0.4.5
icon: https://raw.githubusercontent.com/ipfs/logo/master/raster-generated/ipfs-logo-128-ice-text.png
home: https://ipfs.io/
appVersion: v0.9.1
keywords:
- ipfs
- distributed-web
sources:
- https://github.com/ipfs/go-ipfs
maintainers:
  # TODO: Change maintainers list
  - email: dm3ch@dm3ch.net
    name: dm3ch
