config:
  ethereum:
    url: url
    address: address
    mnemonic: mnemonic
  graphNodeEndpoints:
    admin: http://graphprotocol-node-index:8020/
    status: http://graphprotocol-node-index:8030/graphql
    query: http://graphprotocol-node-query:8000/

postgres:
  db: database
  host: host
  user: user
  password:
    value: password

service:
  annotations:
    test: "test"
